query ListApiKeys {
  apiKeys {
    id
    name
    start
    prefix
    organizationId
    enabled
    expiresAt
    permissions
    metadata
    createdAt
    updatedAt
  }
}

query GetApiKey($id: String!) {
  apiKey(id: $id) {
    id
    name
    start
    prefix
    organizationId
    enabled
    expiresAt
    permissions
    metadata
    createdAt
    updatedAt
  }
}

mutation CreateApiKey($name: String, $prefix: String, $metadata: String) {
  createApiKey(name: $name, prefix: $prefix, metadata: $metadata) {
    id
    name
    start
    prefix
    key
    organizationId
    enabled
    expiresAt
    permissions
    metadata
    createdAt
    updatedAt
  }
}

mutation UpdateApiKey($id: String!, $name: String, $metadata: String) {
  updateApiKey(id: $id, name: $name, metadata: $metadata) {
    id
    name
    start
    prefix
    organizationId
    enabled
    expiresAt
    permissions
    metadata
    createdAt
    updatedAt
  }
}

mutation DeleteApiKey($id: String!) {
  deleteApiKey(id: $id)
}
