// Auto-generated file - DO NOT EDIT
// Generated by scripts/generate-migrations-index.ts

import * as migration_0 from "../migrations/001_initial_schema.ts";
import * as migration_1 from "../migrations/002_auth_schema.ts";
import * as migration_2 from "../migrations/20251115_0952_apikey_schema.ts";

export const migrations = {
  "001_initial_schema": migration_0,
  "002_auth_schema": migration_1,
  "20251115_0952_apikey_schema": migration_2,
};
