// Auto-generated file - DO NOT EDIT
// Generated by scripts/generate-migrations-index.ts

import * as migration_0 from "../migrations/001_initial_schema.ts";
import * as migration_1 from "../migrations/002_auth_schema.ts";
import * as migration_2 from "../migrations/20251115_0952_apikey_schema.ts";
import * as migration_3 from "../migrations/20251115_2105_integrations_schema.ts";
import * as migration_4 from "../migrations/20251116_1200_subroutine_org_integrations.ts";
import * as migration_5 from "../migrations/20251125165000_add_mcp_session.ts";
import * as migration_6 from "../migrations/20251125_connected_account_viewerid.ts";

export const migrations = {
  "001_initial_schema": migration_0,
  "002_auth_schema": migration_1,
  "20251115_0952_apikey_schema": migration_2,
  "20251115_2105_integrations_schema": migration_3,
  "20251116_1200_subroutine_org_integrations": migration_4,
  "20251125165000_add_mcp_session": migration_5,
  "20251125_connected_account_viewerid": migration_6,
};
