x-common-args: &common-args
  CI: true
  BUILD_SHA: ${BUILD_SHA:-}

services:
  sandbox:
    volumes: !reset []
    build:
      target: prod
      args:
        <<: *common-args
  api:
    volumes: !reset
      - ./example.config.yaml:/app/config.yaml:ro
    build:
      target: prod
      args:
        <<: *common-args

  admin-panel:
    volumes: !reset
      - ./example.config.yaml:/app/admin-panel/config.yaml:ro
    build:
      target: prod
      args:
        <<: *common-args

  tests:
    build:
      target: ci
