x-release-build: &release-build
  build:
    args:
      CI: true
      BUILD_SHA: ${BUILD_SHA:-}
    target: prod

services:
  admin-panel:
    <<: *release-build
    volumes: !reset []
    image: ${GHCR_IMAGE_PREFIX:-ghcr.io/local/subroutine}-admin-panel:${IMAGE_TAG:-dev}

  api:
    volumes: !reset []
    <<: *release-build
    image: ${GHCR_IMAGE_PREFIX:-ghcr.io/local/subroutine}-api:${IMAGE_TAG:-dev}

  sandbox:
    volumes: !reset []
    <<: *release-build
    image: ${GHCR_IMAGE_PREFIX:-ghcr.io/local/subroutine}-sandbox:${IMAGE_TAG:-dev}
