services:
  sandbox:
    build:
      context: .
      dockerfile: ./sandbox/Dockerfile
    ports:
      - "3000:3000"
    expose:
      - 3000
    volumes:
      - ./sandbox:/app/sandbox
      - ./eslint:/app/eslint
  
  tests:
    build:
      context: .
      dockerfile: ./tests/Dockerfile
    depends_on:
      - sandbox
