import type { Kysely } from "kysely";
import { sql } from "kysely";

// Migration generated by better-auth CLI
// Auto-converted from SQL to TypeScript format

export const up = async (db: Kysely<any>): Promise<void> => {
  await sql`create table "apikey" ("id" text not null primary key, "name" text, "start" text, "prefix" text, "key" text not null, "userId" text not null references "user" ("id") on delete cascade, "refillInterval" integer, "refillAmount" integer, "lastRefillAt" timestamptz, "enabled" boolean, "rateLimitEnabled" boolean, "rateLimitTimeWindow" integer, "rateLimitMax" integer, "requestCount" integer, "remaining" integer, "lastRequest" timestamptz, "expiresAt" timestamptz, "createdAt" timestamptz not null, "updatedAt" timestamptz not null, "permissions" text, "metadata" text, "organizationId" text not null references "organization" ("id") on delete cascade);`.execute(db);
};

export const down = async (db: Kysely<any>): Promise<void> => {
  // Add rollback logic here if needed
  // For better-auth tables, you typically don't want to drop them
  console.warn("No down migration defined for 2025-11-15T04-06-21.240Z.ts");
};
