#!/usr/bin/env -S deno run --allow-read --allow-write --allow-run --allow-env

import { getLogger } from "../utils/logger.ts";
const logger = getLogger("scripts.better-auth-generate");

const sqlDir = "better-auth_migrations";
const tsDir = "migrations";

const DATABASE_URL =
  Deno.env.get("DATABASE_URL") || "postgresql://subroutine:subroutine@localhost:5432/subroutine";

const command = new Deno.Command("deno", {
  args: [
    "run",
    "--allow-all",
    "--node-modules-dir",
    "npm:@better-auth/cli@latest",
    "generate",
    "--yes",
  ],
  env: {
    ...Deno.env.toObject(),
    DATABASE_URL,
  },
  stdout: "inherit",
  stderr: "inherit",
});

const { code } = await command.output();

if (code !== 0) {
  logger.error("❌ Failed to generate migration");
  Deno.exit(code);
}

for await (const entry of Deno.readDir(sqlDir)) {
  if (!entry.isFile || !entry.name.endsWith(".sql")) continue;

  const sqlPath = `${sqlDir}/${entry.name}`;
  const sqlContent = await Deno.readTextFile(sqlPath);

  const tsFilename = entry.name.replace(".sql", ".ts");
  const tsPath = `${tsDir}/${tsFilename}`;

  const tsContent = `import type { Kysely } from "kysely";
import { sql } from "kysely";

// Migration generated by better-auth CLI
// Auto-converted from SQL to TypeScript format

export const up = async (db: Kysely<any>): Promise<void> => {
  await sql\`${sqlContent.trim()}\`.execute(db);
};

export const down = async (db: Kysely<any>): Promise<void> => {
  // Add rollback logic here if needed
  // For better-auth tables, you typically don't want to drop them
  console.warn("No down migration defined for ${tsFilename}");
};
`;

  await Deno.writeTextFile(tsPath, tsContent);
  await Deno.remove(sqlPath);
}

try {
  await Deno.remove(sqlDir);
} catch {
  // ignore
}

logger.info("moved migration to the ts folder");
