/**
 * Generates a migrations index file that imports and exports all migrations.
 * This allows migrations to be bundled into the compiled binary.
 */

import { join } from "node:path";

const migrationsDir = join(new URL(".", import.meta.url).pathname, "../migrations");

const migrationFiles: string[] = [];
for await (const entry of Deno.readDir(migrationsDir)) {
  if (entry.isFile && entry.name.endsWith(".ts")) {
    migrationFiles.push(entry.name);
  }
}

// Sort to ensure consistent order
migrationFiles.sort();

// Generate the TypeScript code
const imports = migrationFiles
  .map((filename, index) => {
    return `import * as migration_${index} from "../migrations/${filename}";`;
  })
  .join("\n");

const exportsObj = migrationFiles
  .map((filename, index) => {
    const migrationName = filename.replace(/\.ts$/, "");
    return `  "${migrationName}": migration_${index},`;
  })
  .join("\n");

const content = `// Auto-generated file - DO NOT EDIT
// Generated by scripts/generate-migrations-index.ts

${imports}

export const migrations = {
${exportsObj}
};
`;

const outputPath = join(new URL(".", import.meta.url).pathname, "../db/migrations-index.ts");

await Deno.writeTextFile(outputPath, content);

console.log(`Generated migrations index with ${migrationFiles.length} migrations`);
console.log(`Output: ${outputPath}`);
