/**
 * Generates a migrations index file that imports and exports all migrations.
 * This allows migrations to be bundled into the compiled binary.
 */

import { join } from "node:path";
import { getLogger } from "../utils/logger.ts";
const logger = getLogger("api/scripts/generate-migrations-index.ts");


const migrationsDir = join(new URL(".", import.meta.url).pathname, "../migrations");

const migrationFiles: string[] = [];
for await (const entry of Deno.readDir(migrationsDir)) {
  if (entry.isFile && entry.name.endsWith(".ts")) {
    migrationFiles.push(entry.name);
  }
}

// Sort to ensure consistent order
migrationFiles.sort();

const exportsObj = migrationFiles
  .map((filename) => {
    const migrationName = filename.replace(/\.ts$/, "");
    return `  "${migrationName}": import("../migrations/${filename}"),`;
  })
  .join("\n");

const content = `// Auto-generated file - DO NOT EDIT
// Generated by scripts/generate-migrations-index.ts

export const migrations = {
${exportsObj}
};
`;

const outputPath = join(new URL(".", import.meta.url).pathname, "../db/migrations-index.ts");

await Deno.writeTextFile(outputPath, content);

logger.info(`Generated migrations index with ${migrationFiles.length} migrations`);
logger.info(`Output: ${outputPath}`);
