name: Typecheck

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  deno-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x

      - name: Deno install
        run: deno install
        working-directory: ./

      - name: Typecheck
        run: deno check
        working-directory: ./

      - name: Lint
        run: deno lint
        working-directory: ./

      - name: Eslint
        run: deno task eslint

      - name: Prettier check
        run: deno task prettier:check
